import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#854df50a]">
      <body className={inter.className }>
        <div className='max-w-6xl mx-auto '>
        <Nav />
        {children}
        </div>
      </body>
    </html>
  );
}
